<div class="row">
  <div class="col-md-12">
    <div class="box">
      
      <div class="box-header">
        <h3 class="box-title">Quality of Progress Reporting </h3>
        <?= $this->tag->linkTo(
            array("report/new/".$projectID, 
                  "<i class='fa fa-credit-card'></i> Add New Report", 
                  "class" => "btn btn-success pull-right")
            ); 
        ?>        
      </div><!-- /.box-header -->
      
      <div class="box-body">
        <table id="project-quality-report-table" class="table table-bordered table-striped">                   
        </table>
      </div><!-- /.box-body -->

    </div><!-- /.box -->

  </div>
</div>