<div class="row">
  <div class="col-md-12">
    <div class="box">
      
      <div class="box-header">
        <h3 class="box-title">Quality of Progress Reporting </h3>

        <button type='button' class='btn btn-success pull-right' id="createReportButton">
          <i class='fa fa-credit-card'></i> Add New Report
        </button>
        

      </div><!-- /.box-header -->
      
      <div class="box-body">
        <div ><h4> PROJECT <?php print "(".$project->projectID.") ". $project->ProjTitle; ?></h4> </div>
        <table id="projects-report-table" class="table table-bordered table-striped">                   
        </table>

        
      </div><!-- /.box-body -->

    </div><!-- /.box -->

  </div>
</div>


<div class="modal fade custom-width" id="create-report-modal"  role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Create Assessment Report</h4>
      </div>
      <div class="modal-body">
        <h4> <?=$project->ProjTitle ?></h4>

        <?= $this->tag->form(array("reporting/report/new/".$project->id, "method"=>"post")) ?>

          <div class="form-group">
            <label for="descInput">Description</label>;  
            <?php echo $form->render("desc"); ?>  
          </div>

          <div class="form-group">
            <label for="notesInput">Notes</label>;  
            <?php echo $form->render("notes"); ?>  
          </div>

          <button type="submit" class="btn btn-primary">Submit</button>
        
        </form>

      </div>
      
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->