<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title"><b>Create Assessment Report</b></h3>
    <h4> <?=$project->ProjTitle ?></h4>
  </div><!-- /.box-header -->
                
  <?= $this->tag->form(array("reporting/report/new/".$project->id, "method"=>"post")) ?>
  <div class="box-body">

    
    <div class="form-group">
      <label for="descInput">Desc</label>;  
      <?php echo $form->render("desc"); ?>  
    </div>

    <div class="form-group">
      <label for="notesInput">Notes</label>;  
      <?php echo $form->render("notes"); ?>  
    </div>
      
    </div><!-- /.box-body -->

    <div class="box-footer">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
</div><!-- /.box -->