<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Add Item Score</h3>
  </div><!-- /.box-header -->
                
  
  <div class="box-body">
  
    <!--<div class="row">
      <div class="col-xs-4">
        <label for="assessmentInput">Assessment</label>;  
        <?php //echo $form->render("assessmentScale"); ?>  
      </div>  
    </div> --> 

    <?//= $this->tag->form(array("reporting/report/score/".$projectID."/".$itemID, "method"=>"post")) ?>
    <form>
      <div class="row">
        <div class="col-xs-1">
          <label for="scoreInput">Score</label>;  
          <?php echo $form->render("score"); ?>  
        </div>  
      </div>  

      <div class="row">
        <div class="col-xs-10">
          <label for="commentsInput">Comments</label>;  
          <?php echo $form->render("comments"); ?>  
        </div>
      </div>

      
      </div><!-- /.box-body -->

      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Save</button>
      </div>
    </form>
</div><!-- /.box -->